on: [push]

jobs:
  test:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download riscv-toolchain
        uses: ./
      - name: check the toolchain
        run: which riscv64-unknown-elf-objdump